version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: banca-postgres
    environment:
      POSTGRES_DB: banca_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banca_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  banca-backend:
    image: banca-backend:1.0
    container_name: banca-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: banca-backend
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    ports:
      - "8080:8080"

volumes:
  pgdata:
